### ISSUE TITLE
getting a getUserMedia error

### ISSUE THREAD

**Issue by shaikhalid007** [nanomosfet/WebRTC-Flask-server#1]

**Comment by DevJhns** [comment]
@shaikhalid007 have u solved this issue?
nevermind, fixed it and few other things, now need to fix some logics, get into and and rewrite for self use, too many code for just chat and video streams, as i think

**Comment by Unagwu-Chimezie** [comment]
Am getting same  `errors

**Comment by DevJhns** [comment]
> Am getting same `errors

U need to use ssl certs to get user media, 
or u need to use chrome with disabled security headers,
also u need to remove one condition in maybestart, to be able to start call, change some handlers to current with documentation(like stream, u need get tracks, offer and answer functions etc)(disconect handler is outdated, so it woun't even work, others works in chrome and opera) 
good luck!
